<Project Sdk="Dalamud.NET.Sdk/14.0.2">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Platforms>x64</Platforms>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>

		<PackageId>DutySpeed</PackageId>
		<Version>1.2.0.0</Version>
		<AssemblyVersion>1.2.0.0</AssemblyVersion>
		<FileVersion>1.2.0.0</FileVersion>

		<DalamudPluginClass>DutySpeed.Plugin</DalamudPluginClass>
		<GenerateDalamudManifest>true</GenerateDalamudManifest>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="DutySpeed.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>